### PR TITLE
Fix icons urls 

### LINKED ISSUE #161: Icons are missing on news comments
See for example https://geokrety.org/newscomments.php?newsid=185

And icon should be present before the first comment username and also on the edit/delete buttons.
untitled

### PR DESCRIPTION
**Pull request by xcodinas**
Closes #161

### CODE REVIEW

**Comment by kumy** [comment]
@xcodinas Thanks for you contribution!

File: website/defektoskop.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ function success($tablica, $logerrors = true, $error_msg = '', $severity = '1',
 background:white;
 padding:10px;
 margin-top:40px;
-	'><img src='".CONFIG_CDN_IMAGES."/success.png' style='display: block; margin-left: auto; margin-right: auto; padding-bottom:10px;'>";
+	'><img src='".CONFIG_CDN_IMAGES."/icons/success.png' style='display: block; margin-left: auto; margin-right: auto; padding-bottom:10px;'>";
```
Comment (boly38) [inline website/defektoskop.php]: Sorry could you remind me which repo is behind https://cdn.geokrety.org ??

Do you confirm, that CDN refers to https://github.com/geokrety/GeoKrety-Static/tree/master/content/ ?

If Yes I got 1 comment:
-`success.png` seems missing, whereas others ressources updated here exists

OK

https://cdn.geokrety.org/images/icons/note10.png

KO

https://cdn.geokrety.org/images/icons/success.png

Comment (kumy) [reply website/defektoskop.php]: > Do you confirm, that CDN refers to https://github.com/geokrety/GeoKrety-Static/tree/master/content/ ?

Exactly. Good catch!!!
